[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "g++"]

[phases.install]
cmds = ["pip install -r requirements-railway.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "uvicorn api.fastapi_endpoints:app --host 0.0.0.0 --port $PORT --workers 2"
